version: '3.8'

services:


  app:
    container_name: blog-app
    image: blog-image
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    container_name: blog-db
    image: postgres:latest
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: admin
    ports:
      - "6001:5432"



