version: '3.8'

services:
  db:
    container_name: blog-db
    image: postgres:latest
    environment:
      POSTGRES_DB: blog-db
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  app:
    container_name: blog-app
    image: blog-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    
      

  



