# Generated by Django 5.0.3 on 2024-09-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_text_artcleitemtext_articleitemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleitemimage',
            name='article',
        ),
        migrations.CreateModel(
            name='ArticleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='post_images')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtcleItemText',
        ),
        migrations.DeleteModel(
            name='ArticleItemImage',
        ),
    ]
