# Generated by Django 5.0.3 on 2024-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articleitemimage_article_articleitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
