# Generated by Django 5.0.3 on 2024-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='hBIjEBwYbzpKIpFlqwBT', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
