# Generated by Django 5.0.3 on 2024-12-19 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_text_alter_article_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='ARxLylXGqtPykzxlSyVf', unique=True),
        ),
        migrations.AddField(
            model_name='articleitem',
            name='source_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.code'),
            preserve_default=False,
        ),
    ]
